Repository DunaevViktor/PoetryPortal, pull requests merged in 2019-01, with the labels that each got.

#3 добавил vscode в gitignore
  .gitignore
Labels: fix

#6 добавил vscode и слеши
  .gitignore
Labels: fix

#9 обновил файл README.md
  README.md
Labels: fix

#13 подключил стихи и шрифты
  public/bootstrap.min.css
  public/fonts/Caveat-Regular.ttf
  public/fonts/Lobster-Regular.ttf
  public/fonts/NotoSans-Regular.ttf
  public/index.html
  src/index.css
Labels: enhancement

#11 Добавил конфиг для хероку сервера, обновил travis-конфиг
  .travis.yml
  deployment/heroku_server.json
Labels: enhancement

#18 исправил импорт css
  public/index.html
Labels: bug
